name: Build
on:
  push:
    branches: 
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push container image
        run: |
          export REGISTRY=gchr.io/mesosphere
          export DOCKER_CLI_EXPERIMENTAL=enabled
          export OUTPUT_TYPE=docker
          make build-container-linux-amd64
